#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

mark_tag = 'fullscreen'
size_prefix = 'was_'

win = JSON.parse(`hyprctl activewindow -j`)
addr = win['address']
width = win['size'][0]

mon = JSON.parse(`hyprctl monitors -j`)
mon_width = mon[0]['width']
tags = win['tags'] || []

if !tags.include?(mark_tag)
  rel = width.to_f / mon_width

  system("hyprctl dispatch tagwindow #{mark_tag} address:#{addr}")
  system("hyprctl dispatch tagwindow #{size_prefix}#{rel.round(4).to_s.sub('.', '_')} address:#{addr}")
  system('hyprctl dispatch layoutmsg colresize 1')

else
  was = tags.find { |t| t.start_with?(size_prefix) }
  if was
    val = was.sub(size_prefix, '').sub('_', '.').to_f.round(3)

    system("hyprctl dispatch tagwindow -- -#{was} address:#{addr}")
    system("hyprctl dispatch layoutmsg colresize #{val}")
  end

  system("hyprctl dispatch tagwindow -- -#{mark_tag} address:#{addr}")
end
